### ISSUE TITLE
Issue with es2015 compiling

### ISSUE THREAD

**Issue by david-treblig** [zeit/async-throttle#3]
I ran into an issue while compiling with WebPack. The ```'use strict';``` declaration from index.js seems to be missing from the beginning of the file which breaks one package I use which uses your package in turn.

Strict mode seems to be needed to be turned on for node to consider es2015 features such as the ```let cur = 0``` at line 6 (node v4.6)

**Comment by TooTallNate** [comment]
Should be fixed by https://github.com/zeit/async-throttle/commit/58b3f955de002e85fa56642c17ffc7091544a8ab
