### ISSUE TITLE
Please bump package version

### ISSUE THREAD

**Issue by evgeniybilyk** [zeit/async-throttle#4]
According to the [documentation](https://docs.npmjs.com/cli/version)

we have to use something like
```bash
npm version update patch -m 'message'
```

As we can see from commit history you did some changes and didn't bump package version, so depending on this package packages are broken now, cuz of babel 'use strict' error.

I can also provide PL for you.

Here we go: #5

**Comment by TooTallNate** [comment]
Published v1.0.0. Let me know if you find any issues!
